FROM ghcr.io/deephaven/server:0.17.0
ENV PYTHONPATH "${PYTHONPATH}:/data/notebooks"
RUN apt-get update -y
RUN apt-get install build-essential python3-dev -y
RUN apt-get update -y
COPY requirements.txt /requirements.txt
RUN pip3 install -r /requirements.txt
ENV PYTHONDONTWRITEBYTECODE 1
